var express = require('express');
var router = express.Router();
var path = require('path');

const glossarylist =[
  {'ID': 1, 'Term':'AIOps (artificial intelligence for IT operations)', 'Description':'This is a method that uses machine learning and AI to improve and automate various parts of IT operations and management. It usually deals with big data.', 'References':'[1] J. Mulder, “Enterprise devops for architects / Mulder, Jeroen.,” Enterprise DevOps for Architects / Mulder, Jeroen. | EBSCOhost, https://openurl.ebsco.com/c/np77rt/EPDB%3Acat00097a%3A14%3A1312062/detailv2?sid=ebsco%3Aplink&amp;id=ebsco%3Acat00097a%3Adeakin.b4727315&amp;x-cgp-token=np77rt (accessed Jul. 21, 2023). '},
  {'ID': 2, 'Term':'Bootstrap', 'Description':'Bootstrap is a framework which is used by the developers in the process of creation of front-ends of websites and applications.This makes responsive web design a reality.', 'References':'[1] A. Ouellette et al., “What is bootstrap? an awesome 2023 beginner’s guide,” CareerFoundry, https://careerfoundry.com/en/blog/web-development/what-is-bootstrap-a-beginners-guide/ (accessed Jul. 21, 2023). '},
  {'ID': 3, 'Term':'express-generator', 'Description':'This is use to quickly create a application skeleton using express library', 'References':'[1] ujju20 and amitsingh2730, “What is express generator ?,” GeeksforGeeks, https://www.geeksforgeeks.org/what-is-express-generator/ (accessed Jul. 21, 2023). '},
  {'ID': 4, 'Term':'Datacentre', 'Description':'A place that offers shared access to programs and data through the use of a network, computing, and storage infrastructure.', 'References':'[1] F. Habte, “What is a data center? the different types of data centers,” Check Point Software, https://www.checkpoint.com/cyber-hub/cyber-security/what-is-data-center/#:~:text=A%20data%20center%20is%20a,%2C%20compute%2C%20and%20storage%20infrastructure. (accessed Jul. 21, 2023). '},
  {'ID': 5, 'Term':'Repository', 'Description':'Its a place where all the codings of the projects can be stored.It is used as a platform to discus and manage the projects.', 'References':'[1] “About repositories,” GitHub Docs, https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories (accessed Jul. 21, 2023). '},
  {'ID': 6, 'Term':'DevOps', 'Description':'Software development (dev) and operations (ops) are combined to form DevOps. By fostering a culture of collaboration and shared accountability, it is described as a software engineering process that strives to combine the work of development teams with operations teams.', 'References':'[1] E. Freeman, “DevOps,” Amazon, https://aws.amazon.com/devops/what-is-devops/#:~:text=DevOps%20is%20the%20combination%20of,development%20and%20infrastructure%20management%20processes. (accessed Jul. 21, 2023). '},
  {'ID': 7, 'Term':'Render', 'Description':'The modern cloud provider for all your apps and websites. It is used by the developers to run their apps and website.', 'References':'[1] “Cloud application hosting for developers,” Render, https://render.com/#:~:text=Render%20is%20a%20unified%20cloud,and%20auto%20deploys%20from%20Git. (accessed Jul. 21, 2023). '},
  {'ID': 8, 'Term':'Microservices ', 'Description':'Microservices is an architectural design for building a distributed application using containers.', 'References':'[1] M. Larsson, “Microservices,” Amazon, https://aws.amazon.com/microservices/#:~:text=Microservices%20are%20an%20architectural%20and,small%2C%20self-contained%20teams. (accessed Jul. 21, 2023). '},
  {'ID': 9, 'Term':'Ansible', 'Description':'Its an open source software which enables infrastructure as codes. It provides powerful automations.', 'References':'[1] Opensource.com, “What is Ansible?,” Opensource.com, https://opensource.com/resources/what-ansible (accessed Jul. 21, 2023). '},
  {'ID': 10, 'Term':'Maven ', 'Description':'Maven is a build automation that is mainly used for java projects.It is an open source build tool', 'References':'[1] I. Gaba, “What is Maven: Here’s what you need to know [updated],” Simplilearn.com, https://www.simplilearn.com/tutorials/maven-tutorial/what-is-maven (accessed Jul. 21, 2023). '},
  {'ID': 11, 'Term':'Azure ', 'Description':'Azure DevOps fosters a collaborative culture and set of practices that bring together software engineers, project managers, and contributors. It enables enterprises to produce and enhance products at a far faster rate than traditional software development methodologies allow. ', 'References':'[1] Sourced Group, “What is azure devops?,” Sourced Group, https://www.sourcedgroup.com/resources/tutorial/what-is-azure-devops/ (accessed Aug. 4, 2023).  '},
  {'ID': 12, 'Term':'Command Line Interfaces  ', 'Description':'The command line interface (CLI) is a text-based interface that allows the user to respond to visual prompts by putting single commands into the interface and getting a response in the same manner. ', 'References':'[1] “Command-line interface,” Wikipedia, https://en.wikipedia.org/wiki/Command-line_interface (accessed Aug. 4, 2023).  '},
  {'ID': 13, 'Term':'Google Cloud ', 'Description':'Google Cloud (also known as Google Cloud Platform or GCP) is a computer resource provider for designing, deploying, and running Web-based applications. ', 'References':'[1] “Google cloud platform,” Wikipedia, https://en.wikipedia.org/wiki/Google_Cloud_Platform (accessed Aug. 4, 2023).  '},
  {'ID': 14, 'Term':'DevOps Pipeline ', 'Description':'A DevOps pipeline is a collection of automated procedures and technologies that enable developers and operations experts to cooperate on the development and deployment of code to a production environment. ', 'References':'[1] Atlassian, “DevOps pipeline,” Atlassian, https://www.atlassian.com/devops/devops-tools/devops-pipeline#:~:text=A%20DevOps%20pipeline%20is%20a,code%20to%20a%20production%20environment. (accessed Aug. 4, 2023).  '},
  {'ID': 15, 'Term':'Continuous integration ', 'Description':'The method of automating the integration of code changes from various contributors into a single software project is known as continuous integration (CI). Its a fundamental DevOps best practice that allows developers to often merge code changes into a centralized repository where builds and tests are subsequently done. ', 'References':'[1] Atlassian, “What is continuous integration,” Atlassian, https://www.atlassian.com/continuous-delivery/continuous-integration (accessed Aug. 4, 2023).  '},
  {'ID': 16, 'Term':'Collaboration  ', 'Description':'Collaboration in IT refers to a situation in which numerous parties work together to achieve a common goal. The phrase can refer to any technology that enables individuals or groups to collaborate. This encompasses a wide range of technologies, including social and interactive media, as well as other social platforms. ', 'References':' [1] Margaret Rouse&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Margaret Rouse is an award-winning technical writer and teacher known for her ability to explain complex technical subjects simply to a non-technical, M. Rouse, Margaret Rouse is an award-winning technical writer and teacher known for her ability to explain complex technical subjects simply to a non-technical, L. updated: 4 May, and L. updated:, “Collaboration,” Techopedia, https://www.techopedia.com/definition/16895/collaboration#:~:text=In%20an%20IT%20context%2C%20collaboration,media%20and%20other%20social%20platforms. (accessed Aug. 4, 2023). '},
  {'ID': 17, 'Term':'Behaviour Driven Deployment ', 'Description':'Behaviour Driven Development (BDD) is a synthesis and improvement of Test Driven Development (TDD) and Acceptance Test Driven Development (ATDD) approaches. ', 'References':'[1] “Behavior-driven development,” Wikipedia, https://en.wikipedia.org/wiki/Behavior-driven_development (accessed Aug. 4, 2023).  '},
  {'ID': 18, 'Term':'Test Driven Design ', 'Description':' Test Driven Development (TDD) is software development approach in which test cases are developed to specify and validate what the code will do', 'References':'[1] “Test-driven development,” Wikipedia, https://en.wikipedia.org/wiki/Test-driven_development (accessed Aug. 4, 2023).  '},
  {'ID': 19, 'Term':'Acceptance Test Driven Development ', 'Description':'Acceptance Test-Driven Development (ATDD) defines acceptance tests for requirements prior to implementing those requirements. ', 'References':' [1] “Acceptance test-driven development,” Wikipedia, https://en.wikipedia.org/wiki/Acceptance_test-driven_development (accessed Aug. 4, 2023). '},
  {'ID': 20, 'Term':'Continuous Deployment ', 'Description':'Continuous deployment (CD) is a product development process that allows teams to update their products automatically to reflect altered code. ', 'References':'[1] What is Ci/CD?, https://www.redhat.com/en/topics/devops/what-is-ci-cd (accessed Aug. 4, 2023).  '},
  {'ID': 20, 'Term':'Continuous Deployment ', 'Description':'Continuous deployment (CD) is a product development process that allows teams to update their products automatically to reflect altered code. ', 'References':'[1] What is Ci/CD?, https://www.redhat.com/en/topics/devops/what-is-ci-cd (accessed Aug. 4, 2023).  '},
  {'ID': 21, 'Term':' Docker', 'Description':'We use Docker to package, publish, and test our microservices.', 'References':'Davis, Ashley. Bootstrapping Microservices with Docker, Kubernetes, and Terraform : A Project-Based Guide, Manning Publications Co. LLC, 2021. ProQuest Ebook Central, http://ebookcentral.proquest.com/lib/deakin/detail.action?docID=6642516.Created from deakin on 2023-08-27 05:52:39.'},
  {'ID': 22, 'Term':'Docker Registry ', 'Description':'A Docker registry is a server that stores and manages Docker container images, making it possible for users to share, distribute, and deploy containerized applications across several environments.', 'References':'[1] “Docker registries,” Aqua, https://www.aquasec.com/cloud-native-academy/docker-container/docker-registry/#:~:text=A%20Docker%20registry%20is%20a%20system%20for%20versioning%2C%20storing%20and,AWS%20and%20Google%27s%20own%20registries. (accessed Aug. 27, 2023). '},
  {'ID': 23, 'Term':'Container ', 'Description':'A container is a way of virtualizing a server', 'References':'Davis, Ashley. Bootstrapping Microservices with Docker, Kubernetes, and Terraform : A Project-Based Guide, Manning Publications Co. LLC, 2021. ProQuest Ebook Central, http://ebookcentral.proquest.com/lib/deakin/detail.action?docID=6642516.Created from deakin on 2023-08-27 05:54:09.'},
  {'ID': 24, 'Term':'Virtual Machines ', 'Description':'A virtual machine (VM) is a software-based simulation of a real computer that allows several operating systems to operate on the same physical machine, hence establishing separate environments for applications and tasks.', 'References':'[1] “Introduction to virtualization: What is a virtual machine?,” Coursera, https://www.coursera.org/articles/what-is-a-virtual-machine?utm_source=gg&amp;utm_medium=sem&amp;utm_campaign=B2C_APAC__Google_FTCOF_googlecerts_arte_PMax_Addtocart&amp;utm_content=Degree&amp;campaignid=20342757356&amp;adgroupid=&amp;device=c&amp;keyword=&amp;matchtype=&amp;network=x&amp;devicemodel=&amp;adpostion=&amp;creativeid=&amp;hide_mobile_promo&amp;gclid=CjwKCAjwxaanBhBQEiwA84TVXGFpW6IkF9g5FKydp_L3unbtRJBlZxa_KZWu5F92KMzW60IFBnJViRoCgo8QAvD_BwE (accessed Aug. 27, 2023). '},
  {'ID': 25, 'Term':' Docker Image', 'Description':'A Docker image is a small, independent executable package that contains all of the code, libraries, and dependencies required to execute a software application in a consistent and isolated environment.', 'References':'[1] A. S. Gillis, “What is a Docker image? introduction and use cases,” IT Operations, https://www.techtarget.com/searchitoperations/definition/Docker-image#:~:text=A%20Docker%20image%20is%20a,virtual%20machine%20(VM)%20environments. (accessed Aug. 27, 2023). '},
  {'ID': 26, 'Term':' kubernetes ', 'Description':'Kubernetes automates container management operational tasks and includes built-in commands for deploying applications, rolling out changes to your applications, scaling your applications up and down to meet changing needs, monitoring your applications, and more—making application management easier.  ', 'References':'[1] “What is kubernetes?&nbsp; |&nbsp; google cloud,” Google, https://cloud.google.com/learn/what-is-kubernetes#:~:text=Kubernetes%20automates%20operational%20tasks%20of,it%20easier%20to%20manage%20applications. (accessed Aug. 27, 2023). '},
  {'ID': 27, 'Term':'Docker tag ', 'Description':'A tag in Docker is a label that is assigned to a specific version of a Docker image, allowing users to identify between different versions of the same image and reference specific image variants when deploying containers.', 'References':'[1] “Docker tag,” Docker Documentation, https://docs.docker.com/engine/reference/commandline/tag/ (accessed Aug. 27, 2023). '},
  {'ID': 28, 'Term':'Docker push ', 'Description':'"Docker push" is a command that uploads (pushes) a Docker image from a local system to a Docker registry, making the image available for others to retrieve and use in various contexts.', 'References':'[1] “Docker push,” Docker Documentation, https://docs.docker.com/engine/reference/commandline/push/#:~:text=Description,valid%20image%20and%20tag%20names. (accessed Aug. 27, 2023). '},
  {'ID': 29, 'Term':'Docker kill', 'Description':'"Docker kill" is a command that is used to terminate a running Docker container by issuing a SIGKILL signal to the containers main process, which instantly stops execution and shuts down the container.', 'References':'[1] “Docker kill,” Docker Documentation, https://docs.docker.com/engine/reference/commandline/kill/#:~:text=Description,ID-prefix%2C%20or%20name. (accessed Aug. 27, 2023). '},
  {'ID': 30, 'Term':'Docker rm ', 'Description':'"Docker rm" is a command that is used to permanently delete one or more stopped Docker containers from the system, freeing up resources and cleaning up the environment.', 'References':'[1] “Docker RM: Working and examples of Docker RM with Rules &amp; Regulations,” EDUCBA, https://www.educba.com/docker-rm/ (accessed Aug. 27, 2023).'},
  {'ID': 31, 'Term':'Cluster ', 'Description':'A set of connected computers that work together to enable load balancing, auto scaling and high availability.', 'References':'[1] P. Kirvan, “What is a cluster? – definition from TechTarget,” WhatIs.com, https://www.techtarget.com/whatis/definition/cluster (accessed Sep. 10, 2023). '},
  {'ID': 32, 'Term':'kubernetes', 'Description':'Kubernetes is a portable, extensible, open source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation. ', 'References':'[1] “Overview,” Kubernetes, https://kubernetes.io/docs/concepts/overview/ (accessed Sep. 10, 2023). '},
  {'ID': 33, 'Term':'Terraform', 'Description':'Terraform is a powerful open-source Infrastructure as Code (IaC) software tool offered by HashiCorp. It facilitates provisioning and managing your infrastructure on-prem and in the cloud. As an open-source tool it can be easily extended with the help of its plugin-based architecture', 'References':'[1] “What is terraform? terraform definition, how terraform works, examples,” Spacelift, https://spacelift.io/blog/what-is-terraform (accessed Sep. 10, 2023). '},
  {'ID': 34, 'Term':'Kubectl ', 'Description':'kubectl explain can be used to get more information about which fields a given resource needs, as well as the meaning behind those fields', 'References':'[1] “Understanding ‘Kubectl explain,’” Understanding “kubectl explain,” https://hugomartins.io/essays/2022/03/understanding-kubectl-explain/#:~:text=kubectl%20explain%20can%20be%20used,the%20meaning%20behind%20those%20fields. (accessed Sep. 10, 2023). '},
  {'ID': 35, 'Term':'Infrastructure ', 'Description':'Information technology (IT) infrastructure are the components required to operate and manage enterprise IT environments. IT infrastructure can be deployed within a cloud computing system, or within an organizations own facilities.', 'References':'[1] “What is IT infrastructure?,” Red Hat - We make open source technologies for the enterprise, https://www.redhat.com/en/topics/cloud-computing/what-is-it-infrastructure#:~:text=Why%20Red%20Hat%3F-,Overview,within%20an%20organization%27s%20own%20facilities. (accessed Sep. 10, 2023). '},
  {'ID': 36, 'Term':'Azure CLI ', 'Description':'The Azure Command-Line Interface (CLI) is a cross-platform command-line tool to connect to Azure and execute administrative commands on Azure resources. It allows the execution of commands through a terminal using interactive command-line prompts or a script.', 'References':'[1] Dbradish-Microsoft, “What is the azure cli?,” Microsoft Learn, https://learn.microsoft.com/en-us/cli/azure/what-is-azure-cli (accessed Sep. 10, 2023). '},
  {'ID': 37, 'Term':'Authentication ', 'Description':'  Verifying the identity of a user, process, or device, often as a prerequisite to allowing access to resources in an information system.', 'References':'[1] C. C. Editor, “Authentication - glossary: CSRC,” CSRC Content Editor, https://csrc.nist.gov/glossary/term/authentication#:~:text=The%20process%20of%20verifying%20the,resources%20in%20an%20information%20system. (accessed Sep. 10, 2023). '},
  {'ID': 38, 'Term':'Vagrant ', 'Description':'Vagrant is a tool for building and managing virtual machine environments in a single workflow. With an easy-to-use workflow and focus on automation, Vagrant lowers development environment setup time, increases production parity, and makes the "works on my machine" excuse a relic of the past.', 'References':'[1] “Introduction: Vagrant: HashiCorp developer,” Introduction | Vagrant | HashiCorp Developer, https://developer.hashicorp.com/vagrant/intro (accessed Sep. 10, 2023). '},
  {'ID': 39, 'Term':'JSON ', 'Description':'JSON (JavaScript Object Notation) is a text-based, human-readable data interchange format used to exchange data between web clients and web servers. The format defines a set of structuring rules for the representation of structured data. JSON is used as an alternative to Extensible Markup Language (XML)', 'References':'[2] A. S. Gillis, “What is JSON? - definition from techtarget.com,” TheServerSide.com, https://www.theserverside.com/definition/JSON-Javascript-Object-Notation#:~:text=JSON%20(JavaScript%20Object%20Notation)%20is,Extensible%20Markup%20Language%20(XML). (accessed Sep. 10, 2023). '},
  {'ID': 40, 'Term':'Infrastructure-as-Code (IaC) ', 'Description':'IaC involves managing and storing your infrastructure in a repository as code, where it can be recreated or rolled back to a past state with the click of a button.', 'References':'[10] “Overview,” Kubernetes, https://kubernetes.io/docs/concepts/overview/ (accessed Sep. 10, 2023). '},



  
]



/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT22 DevOps Glossary', sub:'to my website showing a collecrtion of DevOps terms and their brief descriptions.',names: glossarylist });
});

module.exports = router;
